version: '3'

networks:
  host:

services:
  web:
    image: coffee
    environment:
      - MONGO_URI=mongodb://mongo-data
    networks:
      - host
    ports:
      - 80:80
    links:
      - redis
      - mongo
  redis:
    image: redis
    ports:
    - 6379:6379
  mongo:
    image: bitnami/mongodb
    ports:
    - 27017:27017
    volumes:
    - ./mongo-data/:/bitnami/mongodb/data/db/